local custom_headers = {

	{
		"                                      ",
		"        ,,;;;,'k.'..                  ",
		"        .:,.....'..co0Kd              ",
		"  .xocd..c;. :;...''''..              ",
		"   .;:'..::. o,     .'.               ",
		"    .o,  ::..o'     .'.               ",
		"     ,l' ;c.,l'     '..               ",
		"     .l;.,c.::.     '..               ",
		"      .d''l.o,.    .'.                ",
		"       ,c'l.d'     ...O               ",
		"  ;0xoo,:.o'l'    .cdxdloO            ",
		" '.cxKKKk,',c:cox0KKKKKK0c:O          ",
		"  'dKKKKk,dkKKKKKKKK0KKKKK0::k        ",
		" .;,kKKKcxKKKKKKdx0l0KKKKKKKk,cx      ",
		"l,cxollo,k000KKK....OKKKKKKKKKx,:0l   ",
		".xoKKKK0.d00O:Kc,;,.0KKKKKKKKKKK0l.;lk",
		" .dOKKKO,x0Odx::Olx.:KKKKKKKKKKKKK:kKd",
		"o;dxxddolllodcdoll'  kKKKK00OKKKKKkKKc",
		".koKKKKKKKOxKKKdKo:  .looddkKKKKKKKKK'",
		"   odxxxdddodddlc,..  ,KKKKKKKKKKKKKK ",
		"  ..0KKKKKKKKKdOo'..   ;KKKKK0OKKKKKO ",
		"    l0KKKKOdl:;'.'..   .;KKKK;0KKKKKl ",
		"       .':'     .'..    ',00:cKKKKKK, ",
		"       ;,c.     '...    .'.  cOKKKKK. ",
		"       ':;......'.'...'.       .o0K0  ",
		"                                  tl  ",
		"                                      ",
	},

	{
		"                                                                  ",
		"        ;.          .'c          xXN'                                ",
		"       d.;     .,',;...        .Kx .Kk                               ",
		"     .k. o   o:.    .:        ,N:    dW.                             ",
		"    .c  .o   x.    ;,        lK.      ,X:                            ",
		"   :;   ;o :c.   .:;        kMNKKKKKKKKNM0                           ",
		"  c'  '  lo.   .          .Kx.....WN.....dN;                         ",
		" d.  .Oc:'               lW:      MN      ,Nk                        ",
		"   .   .   . d,;;:c;''; OMKdddddddMWdddddddkMX.                      ",
		"   .:     l 'x     .  .Nkcccc0MccccclllMXlllloNx                     ",
		"  ;c   .  .c'...'    :Ml     dM        M0     .0X                    ",
		";:   .   ..';       OWc......kM........MX.......dN.                  ",
		"  ..               KWWWWMMWWWWMMMMMMMMMMMMMMMMMMMMMx                 ",
		"                 .Xd   .MX      ..WM........0Mc....OK.               ",
		"                oMl    .MX        MM        0M;     cWo              ",
		"               0MKoooooxWNooooooodWWooolllllXWkllllllkW0.            ",
		"             'WK         x:cl:d.x,ol;d,:  :,;;;:'      oNl           ",
		"            dMx         .x Ox:c.o'dk;xK.  0.0.O         .00          ",
		"           KMK::::::::::loloxocoloOddllcclOoOd0::::::::::oNN.        ",
		"                                                               ",
	},

	{
		"                __.;=====;.__                ",
		"            _.=+==++=++=+=+===;.             ",
		"             -=+++=+===+=+=+++++=_           ",
		"        .     -=:``     `--==+=++==.         ",
		"       _vi,    `            --+=++++:        ",
		"      .uvnvi.       _._       -==+==+.       ",
		"     .vvnvnI`    .;==|==;.     :|=||=|.      ",
		"+QmQQmpvvnv; _yYsyQQWUUQQQm #QmQ#:QQQWUV$QQm.",
		" -QQWQWpvvowZ?.wQQQE==<QWWQ/QWQW.QQWW(: jQWQE",
		"  -$QQQQmmU'  jQQQ@+=<QWQQ)mQQQ.mQQQC+;jWQQ@'",
		"   -$WQ8YnI:   QWQQwgQQWV`mWQQ.jQWQQgyyWW@!  ",
		"     -1vvnvv.     `~+++`        ++|+++       ",
		"      +vnvnnv,                 `-|===        ",
		"       +vnvnvns.           .      :=-        ",
		"        -Invnvvnsi..___..=sv=.     `         ",
		"          +Invnvnvnnnnnnnnvvnn;.             ",
		"            ~|Invnvnvvnvvvnnv}+`",
		"               -~|{*l}*|~",
	},
}

return custom_headers
